name: Package and release

on:
  push:
  # Package only when release version pushed
    tags:
      - '**'
      - '!**[ab]+'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # we first have to clone the AddOn project, this is a required step
      - name: Clone project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # gets git history for changelogs

      # another example where we supply additional arguments, this example is specifically to release
      # for the Burning Crusade Classic version of the game and doesn't upload to WoWInterface
      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -g classic -p 350107 -n "{package-name}-{project-version}-era"
